# Lab 9 — Station list and map
Run the notebook cells in order. Each cell performs one step: load data, list station names, import helper functions and filter, extract unique locations, generate/save the interactive map, then embed the saved map and provide a link.

In [1]:
# 1) Imports and load CSV
import pandas as pd
from IPython.display import display, HTML, IFrame

# Load the station CSV (run this cell first)
df = pd.read_csv('station.csv', low_memory=False)
print('Loaded station.csv — rows:', len(df))

Loaded station.csv — rows: 21

In [2]:
# 2) List unique station names
if 'MonitoringLocationName' in df.columns:
    stations = df['MonitoringLocationName'].dropna().unique()
    print(f'Found {len(stations)} unique station names:')
    for s in stations:
        print('-', s)
else:
    print('Column "MonitoringLocationName" not found in station.csv')

Found 21 unique station names:
- LICKING RIVER AT HWY 536 NEAR ALEXANDRIA, KY
- KENTUCKY RIVER AT LOCK 2 AT LOCKPORT, KY
- Salt River at Main Range Rd nr West Point, KY
- Howell Spring
- Knob Creek
- North Branch of Knob Creek
- Sinking Spring
- Bear Creek at Mouth
- Roaring Paunch Creek at Barthell, KY
- Rock Creek at Devil's Creek Rd
- Big South Fork near Stearns, KY (Blue Heron)
- KENTUCKY R @ CARROLLTON KY. MP 4.1
- LICKING R @ COVINGTON KY. MP 4.5
- Ohio River at Markland Lock and Dam MP 531.5
- OHIO RIVER AT MCALPIN LOCK AND DAM, MP 606.8
- Ohio River at Louisville KY MP594
- OHIO R @ MARKLAND DAM KY.MP531.0
- Ohio River at Cincinnati, OH MP477.5
- OHIO RIVER AT MELDAHL LOCK AND DAM, MP 436.2
- OHIO RIVER AT GREENUP LOCK AND DAM, MP 341
- SALT R @ BULLITT KY. MP 0.8

In [3]:
# 3) Import helper functions and filter for water-quality stations
import lab9_station_map as l9

filtered = l9.filter_water_quality(df)
print('Filtered rows:', len(filtered))
display(filtered.head())

Filtered rows: 21

,OrganizationIdentifier,OrganizationFormalName,MonitoringLocationIdentifier,MonitoringLocationName,MonitoringLocationTypeName,MonitoringLocationDescriptionText,HUCEightDigitCode,DrainageAreaMeasure/MeasureValue,DrainageAreaMeasure/MeasureUnitCode,ContributingDrainageAreaMeasure/MeasureValue,...,AquiferName,LocalAqfrName,FormationTypeText,AquiferTypeName,ConstructionDateText,WellDepthMeasure/MeasureValue,WellDepthMeasure/MeasureUnitCode,WellHoleDepthMeasure/MeasureValue,WellHoleDepthMeasure/MeasureUnitCode,ProviderName
0,USGS-KY,USGS Kentucky Water Science Center,USGS-03254520,"LICKING RIVER AT HWY 536 NEAR ALEXANDRIA, KY",Stream,NaN,5100101,3593.0,sq mi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
1,USGS-KY,USGS Kentucky Water Science Center,USGS-03290500,"KENTUCKY RIVER AT LOCK 2 AT LOCKPORT, KY",Stream,NaN,5100205,6180.0,sq mi,5984.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
2,USGS-KY,USGS Kentucky Water Science Center,USGS-03302058,"Salt River at Main Range Rd nr West Point, KY",Stream,NaN,5140102,2790.0,sq mi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWIS
3,11NPSWRD_WQX,National Park Service Water Resources Division,11NPSWRD_WQX-ABLI_HSSS,Howell Spring,Spring,Howell Spring is located just outside the park...,5110001,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET
4,11NPSWRD_WQX,National Park Service Water Resources Division,11NPSWRD_WQX-ABLI_KCKC,Knob Creek,River/Stream,"The park's new lands cross US31E, and for a sh...",5140103,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET

In [4]:
# 4) Extract unique station locations
locations = l9.get_station_locations(filtered)
print('Unique locations:', len(locations))
display(locations.head())
# Optional: save unique locations to CSV
locations.to_csv('unique_locations.csv', index=False)
print('Saved unique_locations.csv')

Unique locations: 21

,MonitoringLocationIdentifier,MonitoringLocationName,Latitude,Longitude
0,USGS-03254520,"LICKING RIVER AT HWY 536 NEAR ALEXANDRIA, KY",38.920342,-84.447995
1,USGS-03290500,"KENTUCKY RIVER AT LOCK 2 AT LOCKPORT, KY",38.438957,-84.963284
2,USGS-03302058,"Salt River at Main Range Rd nr West Point, KY",37.992222,-85.922056
3,11NPSWRD_WQX-ABLI_HSSS,Howell Spring,37.530169,-85.737578
4,11NPSWRD_WQX-ABLI_KCKC,Knob Creek,37.611417,-85.636583

Saved unique_locations.csv

In [5]:
# 5) Generate and save the interactive folium map
m = l9.plot_and_show_map(locations, out_html='station_map.html', open_in_browser=False)
print('Map saved to station_map.html')

Map saved to station_map.html

In [6]:
# 6) Embed the saved interactive map and provide link
display(IFrame('station_map.html', width=900, height=600))
print('Interactive map file: station_map.html')
print('Open this file in your browser for the full interactive experience.')

Interactive map file: station_map.html
Open this file in your browser for the full interactive experience.